version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=your_root_password
      - DB_NAME=your_database
      - DB_DIALECT=mysql
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "/wait-for.sh 127.0.0.1 3306 'npm run dev'"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=your_database
      - MYSQL_USER=your_user
      - MYSQL_PASSWORD=your_password
    volumes:
      - mysql-data:/var/lib/mysql

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      
  cloud-function:
    build: ./cloud-function
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - PORT=8080
    volumes:
      - ./cloud-function:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend

volumes:
  mysql-data: 